name: Go

on:
  push:
    branches: [master]
    paths-ignore: [".github/**", ".gitignore"]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push ' || startsWith(github.head_ref, 'd') }}
    steps:
      - uses: actions/checkout@v2
      
      - name: pr test
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ startsWith(github.head_ref, 'd') }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Dependencies
        run: go mod tidy

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v -o bin ./...
